import './globals.css'
import { Inter } from 'next/font/google';
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
import client from '../../client-header/client';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  )
}
